title: ~perplexedtheta's recipe book
version: 1.0.0
email: jahdobble@llownd.net
description: >- # this means to ignore newlines until "baseurl:"
    "Were it so easy"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

## Blog settings
paginate: 5
paginate_path: "/blog/:num/"
permalink: /blog/:year/:month/:day/:title:output_ext

# Build settings
exclude:
    - node_modules/
    - Gemfile.lock
    - LICENSE
    - package.json
    - package-lock.json
    - README.md
sass:
    style: compressed
plugins:
    - jekyll-feed
